### ISSUE TITLE
There is an issue with your latest tag v2.2.0

### ISSUE THREAD

**Issue by vishalinfyom** [cashfree/cashfree-pg-sdk-php#13]
Check your `CFConfig.php`

`public bool allowExceptionCapture = true` it should be 

`public bool $allowExceptionCapture = true`

**Comment by suhas-cashfree** [comment]
Please use version 2.1.0

**Comment by vishalinfyom** [comment]
Change your docs to `"cashfree/cashfree-pg-php-sdk": "2.1.0"` instead of 

`"cashfree/cashfree-pg-php-sdk": "^2.1.0"`

**Comment by suhas-cashfree** [comment]
Oh yeah yeah
We will change it

**Comment by suhas-cashfree** [comment]
Please migrate to newer SDK
