### ISSUE TITLE
Failed to download

### ISSUE THREAD

**Issue by vishalradio** [cashfree/cashfree-pg-sdk-php#52]
Failed to download php-http/discovery from dist: The zip extension and unzip/7z commands are both missing, skipping.

**Comment by vishalradio** [comment]
In GitDownloader.php line 82:

  git was not found in your PATH, skipping source download

**Comment by prem-cashfree** [comment]
@vishalradio  there is no such file GitDownloader.php in this package. Can you double check your composer.json file. Or share your composer.json file here.

**Comment by suhas-cashfree** [comment]
Closing this for now. Please raise a new ticket if the issue persists
