### ISSUE TITLE
Cashfree Payment Page Not Opening

### ISSUE THREAD

**Issue by Sonubairwa2021** [cashfree/cashfree-pg-sdk-php#53]
We are currently facing an issue with the Cashfree payment gateway integration in our project. Despite following the provided code implementation steps, the payment gateway page is not opening as expected.

**Comment by suhas-cashfree** [comment]
@Sonubairwa2021 
This sdk is only for order creation. To open payment page you have to integrate Js sdk and then open the checkout page

**Comment by suhas-cashfree** [comment]
Please write to care@cashfree.com with your query
