### ISSUE TITLE
Unzip command failed to extract Card.php while composer require, because CARD.php is existing in the same folder

### ISSUE THREAD

**Issue by devidasm** [cashfree/cashfree-pg-sdk-php#69]
- Installing cashfree/cashfree-pg (4.2.3): Extracting archive
 12/13 [=========================>--]  92%    Failed to extract cashfree/cashfree-pg: (1) '/usr/bin/unzip' -qq '/Applications/XAMPP/xamppfiles/htdocs/api/vendor/composer/tmp-7ec8b5dd98f2ab5cfe1e066f10374c74.zip' -d '/Applications/XAMPP/xamppfiles/htdocs/api/vendor/composer/b1e43839'

replace /Applications/XAMPP/xamppfiles/htdocs/api/vendor/composer/b1e43839/cashfree-cashfree-pg-sdk-php-72cec34/lib/Model/Card.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

**Comment by suhas-cashfree** [comment]
Checking this.
Meanwhile can you try with 4.2.1

**Comment by suhas-cashfree** [comment]
@devidasm Can you try 4.2.5

**Comment by devidasm** [comment]
Thank you for the reply I can see that CARD.php is removed in the latest pull (4.2.5), So I hope the issue has been resolved in 4.2.5, Meanwhile, I switched to Implementation using REST APIs, and will use it on future projects

**Comment by suhas-cashfree** [comment]
Sure Sure. Please create a new ticket, if issue persists
